Repository TechUniv2018/ShopSocial, pull requests merged in 2018-03, with the labels that each got.

#35 Migrations and Models for Cart Entity - Done (With added migrations!)
  __tests__/models/CartsWProducts.test.js
  __tests__/models/CartsWSessions.test.js
  __tests__/models/OrderDetails.test.js
  __tests__/models/ProductDetails.test.js
  __tests__/models/UserDetails.test.js
  migrations/20180225134152-create-carts-w-sessions.js
  migrations/20180226063537-create-cart-w-products.js
  models/cartswsessions.js
  models/cartwproducts.js
  models/productdetails.js
  models/userdetails.js
  package.json
  src/tests/api/v1/products/add/addProductById.test.js
  src/tests/api/v1/products/add/addProductsByCategoryAndPrice.test.js
  src/tests/api/v1/products/add/helpers/addProductsToDatabase.test.js
  src/tests/api/v1/products/getProductById.test.js
  src/tests/api/v1/products/getProductsByCategory.test.js
  src/tests/api/v1/products/remove/removeProductByID.test.js
  src/tests/user/userRegistration.test.js
Labels: database, enhancement, must-have

#38 Created seeder for AdminDetails
  package.json
  seeders/20180305125640-feedIntoAdminDetails.js
  src/createAdmin.js
Labels: backend, database, enhancement

#51 Modify register login api
  src/handlers/registrationHandler.js
  src/handlers/userLoginHandler.js
  src/routes/api/v1/cart/addProductToCart.js
  src/routes/api/v1/cart/adduserIdToCart.js
  src/routes/api/v1/cart/helpers/addCartForUserHelper.js
  src/routes/api/v1/cart/helpers/addProductsToCartHelper.js
  src/routes/api/v1/cart/helpers/destroyTogetherCartHelper.js
  src/routes/api/v1/cart/helpers/getProductsInCartHelper.js
  src/routes/api/v1/cart/helpers/getTogetherCartIdHelper.js
  src/routes/api/v1/cart/helpers/removeProductFromCartHelper.js
  src/schemes/registrationValidation.js
  src/tests/user/userLogin.test.js
  src/tests/user/userRegistration.test.js
Labels: backend, enhancement

#52 Bugfix login validation
  config/config.json
  package.json
  src/handlers/userLoginHandler.js
  src/schemes/registrationValidation.js
  src/server.js
Labels: backend, bug

#54 Fixed recurring category name issue in products add seeder
  seeders/20180307125646-add-products.js
Labels: backend, bugfix

#58 Feature cart social
  package-lock.json
  package.json
  src/routes/api/v1/cart/getCartContentsOfSession.js
  src/routes/api/v1/cart/segregateCartContentsOfSession.js
  src/routes/index.js
Labels: backend, enhancement, help wanted

#60 Feature userfriendlist
  migrations/20180313131419-create-friends-details.js
  models/userFriends.js
  src/routes/index.js
  src/routes/user/addFriend.js
  src/routes/user/getFriends.js
  src/tests/user/addFriend.test.js
  src/tests/user/getFriends.test.js
Labels: backend, database, good to have
